# frozen_string_literal: true

# Auto-generated by MockGenerator
require 'webmock'
require 'json'

module CDEKApiClient
  module Testing
    module AutoMocker
      extend WebMock::API
      
      # Sets up WebMock stubs for every generated OpenAPI endpoint
      def self.stub_all_endpoints!(base_url: nil)
        @base_url = base_url || ENV['CDEK_API_URL'] || 'https://api.edu.cdek.ru/v2'
        
        stub_auth

  # POST /v2/oauth/token
fixture_path_v2_oauth_token_post = File.expand_path('fixtures/responses/v2_oauth_token_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_oauth_token_post) ? File.read(fixture_path_v2_oauth_token_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/oauth/token(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/location/suggest/cities
fixture_path_v2_location_suggest_cities_get = File.expand_path('fixtures/responses/v2_location_suggest_cities_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_location_suggest_cities_get) ? File.read(fixture_path_v2_location_suggest_cities_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/location/suggest/cities(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/location/regions
fixture_path_v2_location_regions_get = File.expand_path('fixtures/responses/v2_location_regions_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_location_regions_get) ? File.read(fixture_path_v2_location_regions_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/location/regions(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/location/postalcodes
fixture_path_v2_location_postalcodes_get = File.expand_path('fixtures/responses/v2_location_postalcodes_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_location_postalcodes_get) ? File.read(fixture_path_v2_location_postalcodes_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/location/postalcodes(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/location/coordinates
fixture_path_v2_location_coordinates_get = File.expand_path('fixtures/responses/v2_location_coordinates_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_location_coordinates_get) ? File.read(fixture_path_v2_location_coordinates_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/location/coordinates(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/location/cities
fixture_path_v2_location_cities_get = File.expand_path('fixtures/responses/v2_location_cities_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_location_cities_get) ? File.read(fixture_path_v2_location_cities_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/location/cities(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/print/orders
fixture_path_v2_print_orders_post = File.expand_path('fixtures/responses/v2_print_orders_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_orders_post) ? File.read(fixture_path_v2_print_orders_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/print/orders(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/prealert
fixture_path_v2_prealert_post = File.expand_path('fixtures/responses/v2_prealert_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_prealert_post) ? File.read(fixture_path_v2_prealert_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/prealert(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/orders
fixture_path_v2_orders_get = File.expand_path('fixtures/responses/v2_orders_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_get) ? File.read(fixture_path_v2_orders_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/orders(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/orders
fixture_path_v2_orders_post = File.expand_path('fixtures/responses/v2_orders_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_post) ? File.read(fixture_path_v2_orders_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/orders(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # PATCH /v2/orders
fixture_path_v2_orders_patch = File.expand_path('fixtures/responses/v2_orders_patch_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_patch) ? File.read(fixture_path_v2_orders_patch) : '{}'
stub_request(:patch, %r{#{Regexp.escape(@base_url)}/orders(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/intakes/availableDays
fixture_path_v2_intakes_availableDays_post = File.expand_path('fixtures/responses/v2_intakes_availableDays_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_intakes_availableDays_post) ? File.read(fixture_path_v2_intakes_availableDays_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/intakes/availableDays(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/intakes
fixture_path_v2_intakes_post = File.expand_path('fixtures/responses/v2_intakes_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_intakes_post) ? File.read(fixture_path_v2_intakes_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/intakes(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # PATCH /v2/intakes
fixture_path_v2_intakes_patch = File.expand_path('fixtures/responses/v2_intakes_patch_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_intakes_patch) ? File.read(fixture_path_v2_intakes_patch) : '{}'
stub_request(:patch, %r{#{Regexp.escape(@base_url)}/intakes(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/print/orders/{uuid}
fixture_path_v2_print_orders_uuid_get = File.expand_path('fixtures/responses/v2_print_orders_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_orders_uuid_get) ? File.read(fixture_path_v2_print_orders_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/print/orders/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/prealert/{uuid}
fixture_path_v2_prealert_uuid_get = File.expand_path('fixtures/responses/v2_prealert_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_prealert_uuid_get) ? File.read(fixture_path_v2_prealert_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/prealert/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/orders/{uuid}
fixture_path_v2_orders_uuid_get = File.expand_path('fixtures/responses/v2_orders_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_uuid_get) ? File.read(fixture_path_v2_orders_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/orders/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # DELETE /v2/orders/{uuid}
fixture_path_v2_orders_uuid_delete = File.expand_path('fixtures/responses/v2_orders_uuid_delete_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_uuid_delete) ? File.read(fixture_path_v2_orders_uuid_delete) : '{}'
stub_request(:delete, %r{#{Regexp.escape(@base_url)}/orders/[^/]+(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/delivery/intervals
fixture_path_v2_delivery_intervals_get = File.expand_path('fixtures/responses/v2_delivery_intervals_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_delivery_intervals_get) ? File.read(fixture_path_v2_delivery_intervals_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/delivery/intervals(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/delivery
fixture_path_v2_delivery_post = File.expand_path('fixtures/responses/v2_delivery_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_delivery_post) ? File.read(fixture_path_v2_delivery_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/delivery(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/print/orders/{uuid}.pdf
fixture_path_v2_print_orders_uuid_pdf_get = File.expand_path('fixtures/responses/v2_print_orders_uuid.pdf_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_orders_uuid_pdf_get) ? File.read(fixture_path_v2_print_orders_uuid_pdf_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/print/orders/[^/]+.pdf(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/orders/{orderUuid}/intakes
fixture_path_v2_orders_orderUuid_intakes_get = File.expand_path('fixtures/responses/v2_orders_orderUuid_intakes_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_orderUuid_intakes_get) ? File.read(fixture_path_v2_orders_orderUuid_intakes_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/orders/[^/]+/intakes(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/intakes/{uuid}
fixture_path_v2_intakes_uuid_get = File.expand_path('fixtures/responses/v2_intakes_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_intakes_uuid_get) ? File.read(fixture_path_v2_intakes_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/intakes/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # DELETE /v2/intakes/{uuid}
fixture_path_v2_intakes_uuid_delete = File.expand_path('fixtures/responses/v2_intakes_uuid_delete_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_intakes_uuid_delete) ? File.read(fixture_path_v2_intakes_uuid_delete) : '{}'
stub_request(:delete, %r{#{Regexp.escape(@base_url)}/intakes/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/print/barcodes
fixture_path_v2_print_barcodes_post = File.expand_path('fixtures/responses/v2_print_barcodes_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_barcodes_post) ? File.read(fixture_path_v2_print_barcodes_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/print/barcodes(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/orders/{uuid}/refusal
fixture_path_v2_orders_uuid_refusal_post = File.expand_path('fixtures/responses/v2_orders_uuid_refusal_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_uuid_refusal_post) ? File.read(fixture_path_v2_orders_uuid_refusal_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/orders/[^/]+/refusal(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/delivery/{uuid}
fixture_path_v2_delivery_uuid_get = File.expand_path('fixtures/responses/v2_delivery_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_delivery_uuid_get) ? File.read(fixture_path_v2_delivery_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/delivery/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/orders/{uuid}/clientReturn
fixture_path_v2_orders_uuid_clientReturn_post = File.expand_path('fixtures/responses/v2_orders_uuid_clientReturn_post_202.json', __dir__)
body_content = File.exist?(fixture_path_v2_orders_uuid_clientReturn_post) ? File.read(fixture_path_v2_orders_uuid_clientReturn_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/orders/[^/]+/clientReturn(?:\?|$)})
  .to_return(
    status: 202,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/print/barcodes/{uuid}
fixture_path_v2_print_barcodes_uuid_get = File.expand_path('fixtures/responses/v2_print_barcodes_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_barcodes_uuid_get) ? File.read(fixture_path_v2_print_barcodes_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/print/barcodes/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/print/barcodes/{uuid}.pdf
fixture_path_v2_print_barcodes_uuid_pdf_get = File.expand_path('fixtures/responses/v2_print_barcodes_uuid.pdf_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_print_barcodes_uuid_pdf_get) ? File.read(fixture_path_v2_print_barcodes_uuid_pdf_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/print/barcodes/[^/]+.pdf(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/reverse/availability
fixture_path_v2_reverse_availability_post = File.expand_path('fixtures/responses/v2_reverse_availability_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_reverse_availability_post) ? File.read(fixture_path_v2_reverse_availability_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/reverse/availability(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/photoDocument
fixture_path_v2_photoDocument_post = File.expand_path('fixtures/responses/v2_photoDocument_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_photoDocument_post) ? File.read(fixture_path_v2_photoDocument_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/photoDocument(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/international/package/restrictions
fixture_path_v2_international_package_restrictions_post = File.expand_path('fixtures/responses/v2_international_package_restrictions_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_international_package_restrictions_post) ? File.read(fixture_path_v2_international_package_restrictions_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/international/package/restrictions(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/delivery/estimatedIntervals
fixture_path_v2_delivery_estimatedIntervals_post = File.expand_path('fixtures/responses/v2_delivery_estimatedIntervals_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_delivery_estimatedIntervals_post) ? File.read(fixture_path_v2_delivery_estimatedIntervals_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/delivery/estimatedIntervals(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/calculator/tarifflist
fixture_path_v2_calculator_tarifflist_post = File.expand_path('fixtures/responses/v2_calculator_tarifflist_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_calculator_tarifflist_post) ? File.read(fixture_path_v2_calculator_tarifflist_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/calculator/tarifflist(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/calculator/tariff
fixture_path_v2_calculator_tariff_post = File.expand_path('fixtures/responses/v2_calculator_tariff_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_calculator_tariff_post) ? File.read(fixture_path_v2_calculator_tariff_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/calculator/tariff(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/calculator/tariffAndService
fixture_path_v2_calculator_tariffAndService_post = File.expand_path('fixtures/responses/v2_calculator_tariffAndService_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_calculator_tariffAndService_post) ? File.read(fixture_path_v2_calculator_tariffAndService_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/calculator/tariffAndService(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/registries
fixture_path_v2_registries_get = File.expand_path('fixtures/responses/v2_registries_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_registries_get) ? File.read(fixture_path_v2_registries_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/registries(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/photoDocument/{uuid}
fixture_path_v2_photoDocument_uuid_get = File.expand_path('fixtures/responses/v2_photoDocument_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_photoDocument_uuid_get) ? File.read(fixture_path_v2_photoDocument_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/photoDocument/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/passport
fixture_path_v2_passport_get = File.expand_path('fixtures/responses/v2_passport_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_passport_get) ? File.read(fixture_path_v2_passport_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/passport(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/deliverypoints
fixture_path_v2_deliverypoints_get = File.expand_path('fixtures/responses/v2_deliverypoints_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_deliverypoints_get) ? File.read(fixture_path_v2_deliverypoints_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/deliverypoints(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/deliverypoints/byPolygons
fixture_path_v2_deliverypoints_byPolygons_get = File.expand_path('fixtures/responses/v2_deliverypoints_byPolygons_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_deliverypoints_byPolygons_get) ? File.read(fixture_path_v2_deliverypoints_byPolygons_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/deliverypoints/byPolygons(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/check
fixture_path_v2_check_get = File.expand_path('fixtures/responses/v2_check_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_check_get) ? File.read(fixture_path_v2_check_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/check(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/calculator/alltariffs
fixture_path_v2_calculator_alltariffs_get = File.expand_path('fixtures/responses/v2_calculator_alltariffs_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_calculator_alltariffs_get) ? File.read(fixture_path_v2_calculator_alltariffs_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/calculator/alltariffs(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/webhooks
fixture_path_v2_webhooks_get = File.expand_path('fixtures/responses/v2_webhooks_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_webhooks_get) ? File.read(fixture_path_v2_webhooks_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/webhooks(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # POST /v2/webhooks
fixture_path_v2_webhooks_post = File.expand_path('fixtures/responses/v2_webhooks_post_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_webhooks_post) ? File.read(fixture_path_v2_webhooks_post) : '{}'
stub_request(:post, %r{#{Regexp.escape(@base_url)}/webhooks(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # GET /v2/webhooks/{uuid}
fixture_path_v2_webhooks_uuid_get = File.expand_path('fixtures/responses/v2_webhooks_uuid_get_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_webhooks_uuid_get) ? File.read(fixture_path_v2_webhooks_uuid_get) : '{}'
stub_request(:get, %r{#{Regexp.escape(@base_url)}/webhooks/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )

  # DELETE /v2/webhooks/{uuid}
fixture_path_v2_webhooks_uuid_delete = File.expand_path('fixtures/responses/v2_webhooks_uuid_delete_200.json', __dir__)
body_content = File.exist?(fixture_path_v2_webhooks_uuid_delete) ? File.read(fixture_path_v2_webhooks_uuid_delete) : '{}'
stub_request(:delete, %r{#{Regexp.escape(@base_url)}/webhooks/[^/]+(?:\?|$)})
  .to_return(
    status: 200,
    body: body_content,
    headers: { 'Content-Type' => 'application/json' }
  )
      end
      
      def self.stub_auth
        base_without_v2 = @base_url.sub(%r{/v2/?$}, '')
        stub_request(:post, %r{#{Regexp.escape(base_without_v2)}/v2/oauth/token.*})
          .to_return(
            status: 200,
            body: {
              access_token: 'mock_access_token_12345',
              token_type: 'bearer',
              expires_in: 3599,
              scope: '',
              jti: 'mock_jti_12345'
            }.to_json,
            headers: { 'Content-Type' => 'application/json' }
          )
      end
    end
  end
end
