# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class Office < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] code
      #   @return [String]
      attribute? :code, Types::String.optional
      # @!attribute [r] uuid
      #   @return [String]
      attribute? :uuid, Types::String.optional
      # @!attribute [r] address_comment
      #   @return [String]
      attribute? :address_comment, Types::String.optional
      # @!attribute [r] nearest_station
      #   @return [String]
      attribute? :nearest_station, Types::String.optional
      # @!attribute [r] nearest_metro_station
      #   @return [String]
      attribute? :nearest_metro_station, Types::String.optional
      # @!attribute [r] work_time
      #   @return [String]
      attribute? :work_time, Types::String.optional
      # @!attribute [r] phones
      #   @return [Array<Hash>]
      attribute? :phones, Types::Array.of(Types::Hash).optional
      # @!attribute [r] email
      #   @return [String]
      attribute? :email, Types::String.optional
      # @!attribute [r] note
      #   @return [String]
      attribute? :note, Types::String.optional
      # @!attribute [r] type
      #   @return [String]
      attribute? :type, Types::String.optional
      # @!attribute [r] owner_code
      #   @return [String]
      attribute? :owner_code, Types::String.optional
      # @!attribute [r] take_only
      #   @return [Boolean]
      attribute? :take_only, Types::Bool.optional
      # @!attribute [r] is_handout
      #   @return [Boolean]
      attribute? :is_handout, Types::Bool.optional
      # @!attribute [r] is_reception
      #   @return [Boolean]
      attribute? :is_reception, Types::Bool.optional
      # @!attribute [r] is_dressing_room
      #   @return [Boolean]
      attribute? :is_dressing_room, Types::Bool.optional
      # @!attribute [r] is_marketplace
      #   @return [Boolean]
      attribute? :is_marketplace, Types::Bool.optional
      # @!attribute [r] is_ltl
      #   @return [Boolean]
      attribute? :is_ltl, Types::Bool.optional
      # @!attribute [r] have_cashless
      #   @return [Boolean]
      attribute? :have_cashless, Types::Bool.optional
      # @!attribute [r] have_cash
      #   @return [Boolean]
      attribute? :have_cash, Types::Bool.optional
      # @!attribute [r] have_fast_payment_system
      #   @return [Boolean]
      attribute? :have_fast_payment_system, Types::Bool.optional
      # @!attribute [r] allowed_cod
      #   @return [Boolean]
      attribute? :allowed_cod, Types::Bool.optional
      # @!attribute [r] site
      #   @return [String]
      attribute? :site, Types::String.optional
      # @!attribute [r] office_image_list
      #   @return [Array<Hash>]
      attribute? :office_image_list, Types::Array.of(Types::Hash).optional
      # @!attribute [r] work_time_list
      #   @return [Array<Hash>]
      attribute? :work_time_list, Types::Array.of(Types::Hash).optional
      # @!attribute [r] work_time_exception_list
      #   @return [Array<Hash>]
      attribute? :work_time_exception_list, Types::Array.of(Types::Hash).optional
      # @!attribute [r] weight_min
      #   @return [Float, Integer]
      attribute? :weight_min, (Types::Float | Types::Integer).optional
      # @!attribute [r] weight_max
      #   @return [Float, Integer]
      attribute? :weight_max, (Types::Float | Types::Integer).optional
      # @!attribute [r] dimensions
      #   @return [Array<Hash>]
      attribute? :dimensions, Types::Array.of(Types::Hash).optional
      # @!attribute [r] status
      #   @return [String]
      attribute? :status, Types::String.optional
      # @!attribute [r] errors
      #   @return [Array<Hash>]
      attribute? :errors, Types::Array.of(Types::Hash).optional
      # @!attribute [r] warnings
      #   @return [Array<Hash>]
      attribute? :warnings, Types::Array.of(Types::Hash).optional
      # @!attribute [r] location
      #   @return [Object]
      attribute? :location, Types::Any.optional
      # @!attribute [r] distance
      #   @return [Integer]
      attribute? :distance, Types::Integer.optional
      # @!attribute [r] ltl_acceptance_partners
      #   @return [Boolean]
      attribute? :ltl_acceptance_partners, Types::Bool.optional
      # @!attribute [r] ltl_issuance_partners
      #   @return [Boolean]
      attribute? :ltl_issuance_partners, Types::Bool.optional
      # @!attribute [r] fulfillment
      #   @return [Boolean]
      attribute? :fulfillment, Types::Bool.optional
      # @!attribute [r] length_max
      #   @return [Integer]
      attribute? :length_max, Types::Integer.optional
      # @!attribute [r] width_max
      #   @return [Integer]
      attribute? :width_max, Types::Integer.optional
      # @!attribute [r] height_max
      #   @return [Integer]
      attribute? :height_max, Types::Integer.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
