# frozen_string_literal: true

require 'dry-struct'
require_relative 'types'
require_relative 'sender'
require_relative 'recipient'
require_relative 'service'
require_relative 'package'

module CDEKApiClient
  module Entities
    # Auto-generated by EntityGenerator based on CDEK OpenAPI Schema
    class OrderData < Dry::Struct
      transform_keys(&:to_sym)

      # @!attribute [r] type
      #   @return [Integer]
      attribute? :type, Types::Integer.optional
      # @!attribute [r] additional_order_types
      #   @return [Array]
      attribute? :additional_order_types, Types::Array.of(Types::Integer).optional
      # @!attribute [r] number
      #   @return [String]
      attribute? :number, Types::String.optional
      # @!attribute [r] accompanying_number
      #   @return [String]
      attribute? :accompanying_number, Types::String.optional
      # @!attribute [r] tariff_code
      #   @return [Integer]
      attribute? :tariff_code, Types::Integer.optional
      # @!attribute [r] comment
      #   @return [String]
      attribute? :comment, Types::String.optional
      # @!attribute [r] shipment_point
      #   @return [String]
      attribute? :shipment_point, Types::String.optional
      # @!attribute [r] delivery_point
      #   @return [String]
      attribute? :delivery_point, Types::String.optional
      # @!attribute [r] date_invoice
      #   @return [String]
      attribute? :date_invoice, Types::String.optional
      # @!attribute [r] shipper_name
      #   @return [String]
      attribute? :shipper_name, Types::String.optional
      # @!attribute [r] shipper_address
      #   @return [String]
      attribute? :shipper_address, Types::String.optional
      # @!attribute [r] delivery_recipient_cost
      #   @return [Object]
      attribute? :delivery_recipient_cost, Types::Any.optional
      # @!attribute [r] delivery_recipient_cost_adv
      #   @return [Array<Hash>]
      attribute? :delivery_recipient_cost_adv, Types::Array.of(Types::Hash).optional
      # @!attribute [r] sender
      #   @return [Object]
      attribute? :sender, Sender.optional
      # @!attribute [r] seller
      #   @return [Object]
      attribute? :seller, Types::Any.optional
      # @!attribute [r] recipient
      #   @return [Object]
      attribute? :recipient, Recipient.optional
      # @!attribute [r] from_location
      #   @return [Object]
      attribute? :from_location, Types::Any.optional
      # @!attribute [r] to_location
      #   @return [Object]
      attribute? :to_location, Types::Any.optional
      # @!attribute [r] services
      #   @return [Array<Service>]
      attribute? :services, Types::Array.of(Service).optional
      # @!attribute [r] packages
      #   @return [Array<Package>]
      attribute? :packages, Types::Array.of(Package).optional
      # @!attribute [r] delivery_types
      #   @return [Array]
      attribute? :delivery_types, Types::Array.of(Types::String).optional
      # @!attribute [r] print
      #   @return [String]
      attribute? :print, Types::String.optional
      # @!attribute [r] widgetToken
      #   @return [String]
      attribute? :widgetToken, Types::String.optional
      # @!attribute [r] is_client_return
      #   @return [Boolean]
      attribute? :is_client_return, Types::Bool.optional
      # @!attribute [r] has_reverse_order
      #   @return [Boolean]
      attribute? :has_reverse_order, Types::Bool.optional
      # @!attribute [r] developer_key
      #   @return [String]
      attribute? :developer_key, Types::String.optional

      # Converts the object to a hash representation suitable for API requests.
      def to_h
        super.compact
      end

      # Converts the object to a JSON representation.
      def to_json(*_args)
        to_h.to_json
      end
    end
  end
end
